### ISSUE TITLE
Less formatting - variable interpolation and mixins with multiple variables 

### ISSUE THREAD

**Issue by retan** [brackets-beautify/brackets-beautify#222]
LESS files are not aligned properly if:
1. variable interpolation is used.
--- this
```css
.class-@{name} {
    display: block;
}
```
--- becoms this
```css
.class-@ {
    name
}

{
    display: block;
}
```

2. mixins with multiple parameters
--- this
```css
.mymixin(@color: #ccc; @border-width: 1px)  {
    border: @border-width solid @color;
}
```
--- becomes this
```css
.mymixin(@color: #ccc;
@border-width: 1px) {
    border: @border-width solid @color;
}
```
I would appreciate a fix.
(by the way this extension works a way better than the dedicated Format LESS StyleSheet, which outputs a total mess!!)

**Comment by bitwiseman** [comment]
Related to #106. 

@retan - Look at https://github.com/beautify-web/js-beautify and see if you can find corresponding issues there.   If you can't find it, please file an issue there.

@Hirse  - There's no reason the beautifier can't do this, but it obviously doesn't right now.

**Comment by retan** [comment]
@bitwiseman I found an issue about interpolated variables https://github.com/beautify-web/js-beautify/issues/844 ... And it seems it was fixed - or do I understand this wrong: "bitwiseman added this to the v1.6.3 milestone on 23 Feb"?

**Comment by bitwiseman** [comment]
@retan - that was fixed but it looks like your change includes a semicolon instead of comma, so it is a different case.  Open a new issue.

**Comment by retan** [comment]
@bitwiseman Wait a second. The "semicolon issue" has nothing to do with variable interpolation, which, as you say, was fixed... so why doesn't it still work? I'm bewildered.

**Comment by bitwiseman** [comment]
Ah, right so this is why you probably want split these into different issues, so we can talk more clearly about them.  😄 

The variable interpolation is definitely not fixed.  File a bug for that in js-beautify. 

As for the mixins, they're partially fixed, but your input is different from the one that was fixed.
```
// fixed
.mymixin(@abc, @xyz) {
}

// not fixed
.mymixin(@color: #ccc; @border-width: 1px)  {
}
```
Looks like you'll want to file a new (separate) issue in js-beautify for that as well.

**Comment by Hirse** [comment]
@bitwiseman Thanks for handling this.
@retan, When you create new issues, I'll try to follow them closely and update the Extension with new releases of the library.

**Comment by retan** [comment]
@bitwiseman & @Hirse Thank you both. I'll do thatt.
